version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=example
      - DATABASE_NAME=lendsqr
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - lendsqr-be
    command: ['node', 'dist/src/main.js']

  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: lendsqr
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lendsqr-be

volumes:
  db_data:

networks:
  lendsqr-be:
    driver: bridge
